### ISSUE TITLE
این خطا رو بررسی میکنید

### ISSUE THREAD

**Issue by mostafacpr** [deathline94/LazyTunnel#1]
Last login: Wed Jun 14 14:19:15 2023 from 2.147.110.163
root@Span:~# bash <(curl -fsSL https://raw.githubusercontent.com/deathline94/LazyTunnel/main/LazyTunnel.sh)
curl: (6) Could not resolve host: raw.githubusercontent.com
root@Span:~#

**Comment by deathline94** [comment]
شما به نظر میرسه یه بار اسکریپت رو اجرا کردین .در حالی که اسکریپت ران باشه و تونل وصل باشه , سرور در حالت تونل باقی خواهد موند و به اینترنت دسترسی نداره . حالا برای استفاده مجدد قبلش یا باید یک بار سرور ریبوت بشه یا اسکریپت نصب قبلی پاک بشه

**Comment by mostafacpr** [comment]
درسته حق با شماست تشکر

**Comment by deathline94** [comment]
سلامت باشید
